### ISSUE TITLE
Floating point programs test

### ISSUE THREAD

**Issue by Sebas95** [skordal/potato#11]
Potato is a great design and easy to use, thanks for posting it.  I've been testing some floating point code compiled with rv32i, it works in almost cases except when I include floating point operations (or assigments) inside loop scopes, it is like if it is reading wrong data from floating point variables. Does potato has support for those kind of operations with floating point data?

**Comment by skordal** [comment]
There is no support for floating point instructions in the processor. However, it should still be possible to use floating point through software emulation libraries provided by the compiler, which I assume you are doing (what command line options are you using for the compiler?).

It's hard to tell what has gone wrong here, have you checked if there are any floating point instructions in the application you are trying to run? Could you provide a small code snippet that triggers the problem?

**Comment by Sebas95** [comment]
Yes, I use floating point through software emulation libraries provided by the compiler. I've been testing floating point code and it works fine, except in one case, when loops are used; for example:
_______________________________________________________________________________
uint_32 i = 10;
float x = 56;
while (i > 4)
{ 
     x = x -1;
     i = i-1;
}
sendNumberByUart(x); //here assuming that the sender function works correctly (i've tested it)
_____________________________________________________________________________ 
 
Then the sender function sends a corrupted float value. If I  test the same code but using x as an integer it works fine!
Also the following example works fine:
_______________________________________________________________________________
uint_32 i = 10;
float x ;
while (i > 4)
{ 
     x = 56 -1;
     i = i-1
}
sendNumberByUart(x); //here assuming that the sender function works correctly (i've tested it)
_____________________________________________________________________________ 

The issue is related to the first example above. 
I am using the same makefile provided in helloworld example.

Thanks!

**Comment by skordal** [comment]
What assembly code does the compiler generate for the first example?

(Note that the second example simply boils down to `sendNumberByUart(55)`, without the subtraction that the first example does, so there is less room for problems to occur)

**Comment by Sebas95** [comment]
`
float* IcNeighbors(float VD[N],float IC[N],float CONN[N][N])
{
	float V = 0;
	int i,j;
	float Facc = 0;
	float Vacc = 0;
	float f = 0;
	for(i=0;i<N;i++)
	{
		for(j=0;j<N;j++)
		{
			V = VD[i]-VD[j];
			f = V;
			Facc += f*CONN[i][j];
			Vacc += V*CONN[i][j];
		}
		IC[i] = 0.8 * Facc + Vacc * 0.2;
	}
	return IC;
}`

**Comment by Sebas95** [comment]
`
float* IcNeighbors(float VD[N],float IC[N],float CONN[N][N])
{
	float V = 0;
	int i,j;
	float Facc = 0;
	float Vacc = 0;
	float f = 0;
	for(i=0;i<N;i++)
	{
		for(j=0;j<N;j++)
		{
			V = VD[i]-VD[j];
			f = V;
			Facc += f*CONN[i][j];
			Vacc += V*CONN[i][j];
		}
		IC[i] = 0.8 * Facc + Vacc * 0.2;
	}
	return IC;
}`

**Comment by Sebas95** [comment]
float* IcNeighbors(float VD[N],float IC[N],float CONN[N][N])
{
	float V = 0;
	int i,j;
	float Facc = 0;
	float Vacc = 0;
	float f = 0;
	for(i=0;i<N;i++)
	{
		for(j=0;j<N;j++)
		{
			V = VD[i]-VD[j];
			f = V;
			Facc += f*CONN[i][j];
			Vacc += V*CONN[i][j];
		}
		IC[i] = 0.8 * Facc + Vacc * 0.2;
	}
	return IC;
}

**Comment by Sebas95** [comment]
The problem appears when I do some operations inside loops, the real function I'm using is:
![ic](https://user-images.githubusercontent.com/8340986/40851644-4e3f5fc0-6585-11e8-98fb-2389f989f7d7.png)

Then, when I call this functions and try to read IC variable, the IC values are corrupted.

The assembly code generated is:
![image](https://user-images.githubusercontent.com/8340986/40851720-79edd354-6585-11e8-936f-ba7bd22e4088.png)

Then, the complete assembly code is:

[main.txt](https://github.com/skordal/potato/files/2063408/main.txt)

**Comment by Sebas95** [comment]
I've found that -Os flags removes the routine call for floating point operations emulation from IcNeighbors function.
