### ISSUE TITLE
hello exmaple make failed

### ISSUE THREAD

**Issue by bg2d** [skordal/potato#13]
Hello,

I installed riscv-gnu-toolchain in the following way:
`git clone --recursive https://github.com/riscv/riscv-gnu-toolchain`
`./configure --prefix=/opt/riscv --with-arch=rv32gc --with-abi=ilp32d`
`make`

After that I tried to build the hello example. I received the following error:
`cc1: error: requested ABI requires -march to subsume the 'D' extension`

How can I fix it?

Thanks,
Bogdan D.

**Comment by skordal** [comment]
Try compiling with -march=rv32i (see `TARGET_CFLAGS` in  [common.mk](https://github.com/skordal/potato/blob/master/software/common.mk) to see which flags are used to compile Potato applications). The Potato processor does not support any extensions, so you have to use the -march flag to prevent the compiler from using instructions the processor does not understand.

If you are running `make` to compile the example, the -march should already be added to the command line. In that case, you might need to reconfigure the toolchain. Try to build it with
`./configure --prefix=/opt/riscv --with-arch=rv32i --with-abi=ilp32`, to prevent the standard libraries from containing code which requires extensions.

**Comment by bg2d** [comment]
Problem solved. Thank you!
