### ISSUE TITLE
The design failed to meet the timing requirements

### ISSUE THREAD

**Issue by bg2d** [skordal/potato#14]
Hello,

I configured the clock generator and the memory as is described in your documentation. The memory was loaded with hello.coe file. The bitstream was geretated successfully but the project does not work. I do not receive anything on UART. I checked Vivado reports and the design failed to meet the timing requirements. Did you face this problem before? I am using Nexys 4DDR board. Below you have the detailed timing report.

![design_timing_summary](https://user-images.githubusercontent.com/10267203/43674615-a460cc5e-97df-11e8-9410-558e1c94ac21.png)

![inter-clock-paths](https://user-images.githubusercontent.com/10267203/43674617-aff3352a-97df-11e8-9ab8-08942275ec83.png)

![intra-clock-paths](https://user-images.githubusercontent.com/10267203/43674618-b2c3d35e-97df-11e8-9a1d-8b56df73eca2.png)

Thank you,
Bogdan D.

**Comment by skordal** [comment]
I have heard from others having the same problem. In the clocking wizard, in the first tab ("Clocking Options"), you can try to set the Source for the primary input clock to "Global Buffer" instead of "Single ended clock capable pin".

Let me know if it fixes the problem.

**Comment by bg2d** [comment]
Thank you for the solution. After I set the input clock to "Global Buffer" there are no timing constraints violations but I receive nothing on terminal. I do not know exactly what can cause this issue.
