### ISSUE TITLE
hello world example no output

### ISSUE THREAD

**Issue by bg2d** [skordal/potato#15]
Hello,

I followed the steps from example directory. The project was synthesized successfully and .coe file for hello world example was generated as well. If I upload the .bit file I don't receive anything on terminal. Do you know what can cause this issue?

Thank you,
Bogdan D.

**Comment by skordal** [comment]
There could be several reasons for this not working. First check that the terminal settings are correct, the serial port should be configured with the following parameters:
* 115200 baud
* 8 bits per byte
* 1 stop byte
* no parity
* no flow control

Which application are you trying to run?

**Comment by skordal** [comment]
I almost forgot:

Recently, the applications were rewritten so they could be loaded by the bootloader into the application RAM. Try to build the `bootloader` application and load it into the AEE ROM, and see if you get any output.

I am updating the example README.md file to include this information.

**Comment by bg2d** [comment]
Now it works! The bootloader starts properly and the "hello" example is loaded. Thank you for your help!
