### ISSUE TITLE
Clock Generator port Map issue

### ISSUE THREAD

**Issue by riscveval** [skordal/potato#5]
Hi I am following your material to generate clock generator IP. But port Renaming taps not shows the system clock reset and additional clock. Can you give your suggestion to resolve this issue.

**Comment by skordal** [comment]
Hi,

Could you give some more details about your problem? Which version of Vivado are you using for the project?

**Comment by riscveval** [comment]
Hi I am using Vivado 2016.4 version. Port mapping tabs not shows the system clock , peripheral clock and system reset.

**Comment by skordal** [comment]
Sorry for taking a long time to respond. The port remapping tab has been changed in recent versions of Vivado. The clock ports should now be renamed in the "Output Clocks" tab. The example documentation has been updated to reflect this.
