### ISSUE TITLE
Generation of dmem.hex fails

### ISSUE THREAD

**Issue by stdefeber** [skordal/potato#6]
Hello,

I get errors while generating the dmem.hex file using the extract_hex.sh script.
So far I have tracked it down to the required data ending up in the .sdata section.
This probably has to do with the linker script or my (mis)use/lacking knowledge of the tool-chain.

br,

ST

**Comment by skordal** [comment]
It sounds like it could be a linker script issue. The extract_hex.sh script is designed to extract data from the .text and .data sections only. I suggest trying to modify your linker script to place the .sdata (and .sbss) sections inside the .data (and .bss) sections and see if it works.

**Comment by stdefeber** [comment]
Apologies for the late reply.

I am using the default shipped SoC linker-script.
What I also notice is that the .sdata section is half-word aligned.

So I get:

`ffffc000 <gpioRegs>:`
`ffffc000:       2000                    fld     fs0,0(s0)`
`ffffc002:       c000                    sw      s0,0(s0)`
` `
`ffffc004 <timerRegs>:`
`ffffc004:       0000                    unimp`
`ffffc006:       c000                    sw      s0,0(s0)`

In stead of the expected word-aligned

`ffffc000 <gpioRegs>:`
`ffffc000:       c0002000`
` `
`ffffc004 <timerRegs>:`
`ffffc004:       c0000000`

Dumping it with 
`riscv32-unknown-elf-objdump -s -j .sdata riscv_app.elf | sed '1,4d' | awk '!/:$/ { for (i = 2; i < 6; i++) print $i; }' | sed '/^$/d' > test.txt`

Leaves me with 

`002000c0`
`000000c0`

Which is even further from the expected end result :(

**Comment by skordal** [comment]
It almost looks like it is trying to interpret the assembly code as compressed instructions. Which command line arguments are you using when calling GCC?
