### ISSUE TITLE
helloworld application not working anymore

### ISSUE THREAD

**Issue by siorpaes** [skordal/potato#7]
With latest commit e3a862d96fff4f2a6c0cf566931f1602a3790221 helloworld application is not working any longer (no output is visible on UART).
If disabling the cache in the top level the application works fine again.
I am using a Basys3 board.

**Comment by skordal** [comment]
This is probably caused by another cache bug. I am seeing the same when running the SHA256 benchmark application, where the startup banner does not get printed.

I will look into this, thanks for reporting it 👍

**Comment by siorpaes** [comment]
You are welcome! thanks to you for this awesome project. I find it so useful for learning computer architectures :D

**Comment by skordal** [comment]
The latest commits fixes some timing issues with the cache and when resetting the board. It looks like both the SHA256 and Hello World applications should work again now, both when running with or without the cache.

**Comment by siorpaes** [comment]
Great! I'll check this out asap. Thanks
