### ISSUE TITLE
Unsigned store crashes application

### ISSUE THREAD

**Issue by siorpaes** [skordal/potato#8]
While developing a simple peripheral I noticed a quite strange behavior where apparently a branch to __divsi3 never returns. I don't think it's a problem with the application itself at it is extremely basic, it is very data specific and does not occur if changing optimization options.
I am attaching the simplest application I could come up with that triggers the problem (see comments in main.c for more info).
[crashme.tar.gz](https://github.com/skordal/potato/files/1685464/crashme.tar.gz)

**Comment by siorpaes** [comment]
Just tested the application with the simulator and the end result is the same, so not a Potato issue :+1: 
Quite puzzled on what's going on though... If interested here's the simulator traces.

[crash.txt](https://github.com/skordal/potato/files/1685860/crash.txt)
[nocrash.txt](https://github.com/skordal/potato/files/1685861/nocrash.txt)

**Comment by siorpaes** [comment]
It turns out was a toolchain issue. Updating gcc from 6.1.0 to 7.1.0 fixed the problem.

**Comment by skordal** [comment]
I am glad to hear you found a solution :)
